// nature-web/src/containers/Fortune/Fortune.jsx
import Header from "../../components/Header/Header";
import FortuneConversation from "../../components/Chatgpt/FortuneConversation";
import Footer from "../../components/Footer/Footer";
import './Fortune.css';

function Fortune() {

  return (
    <div className="fortune-container">
      <FortuneConversation />
    </div>
  );
}

export default Fortune;

// nature-web-vue/src/pages/fortune/index.vue
<template>
  <div className="fortune-container">
    <FortuneConversation />
  </div>
</template>

<script>
import FortuneConversation from '@/components/fortune/FortuneConversation.vue'

export default {
  components: {
    FortuneConversation,
  },
  setup() {

  }
}
</script>

<style>
@import "@/assets/css/pages/fortune.css";
</style>
