// nature-web-vue/src/components/movie/MovieReview.vue
<template>
  <LoadingBar v-if="!review" />
  <div v-else className="movie-review">
    <p>{{ review }}</p>
  </div>
</template>

<script>
import LoadingBar from '@/app/pages/LoadingBar.vue'
import { toRefs, ref } from 'vue'
import { getReviewApi } from '@/api/movie'

export default {
  props: [
    'title'
  ],
  components: {
    LoadingBar,
  },
  setup(props) {
    const review = ref(null)
    const { title } = toRefs(props)

    const getReview = async () => {
      await getReviewApi(title.value)
        .then(({ data }) => {
          review.value = data.assistant;
        }).catch((error) => {
          console.log(error)
        })
    }
    getReview()

    return {
      review,
    }
  }

}
</script>

// nature-web/src/components/Movie/MovieReview.tsx
import { useEffect, useState } from "react";
import movieAction from "../../actions/movie/actions";
import LoadingBar from "../../app/pages/LoadingBar";

interface OwnProps {
  title: string;
}

function MovieReview({ title }: OwnProps) {
  const [review, setReview] = useState('')

  useEffect(() => {
    console.log("Movie getMovieReview")
    const getReview = () => {
      movieAction.getMovieReview(title)
        .then((data) => {
          console.log("MovieReview", data);
          let answer = data.assistant;
          setReview(answer);
        })
    }
    getReview();
  }, [])

  if (!review) {
    return <LoadingBar />
  }
  return (
    <div className="movie-review">
      <p>{review}</p>
    </div>
  )
}
export default MovieReview;
