// nature-web/src/components/Home/Home.jsx
import './Home.css';
import Resume from './Resume';
import { useRef, useState } from 'react';
import ScrollToTop from '../../app/utils/ScrollToTop';
import * as config from '../../app/config'

function Home() {
  const brcRef = useRef()
  const feRef = useRef()
  const beRef = useRef()
  const resumeRef = useRef()
  const [top, setTop] = useState(0)

  const frontEnd = config.GET_FIREBASE_FILE_URL('nature_web.png');
  const backEnd = config.GET_FIREBASE_FILE_URL('nature_server.png');

  const handleHashMove = (e, ref) => {
    e.preventDefault();
    let breadcrumbHeight = brcRef.current.clientHeight
    let h = ref.current?.offsetTop - (breadcrumbHeight);
    setTop(h)
  }

  return (
    <>
      <ScrollToTop top={top} />
      <div className="home-container">
        <div className="breadcrumb" ref={brcRef}>
          <div className='portfolio-link'>
            <span>포트폴리오 </span>
            <button onClick={(e) => handleHashMove(e, feRef)} >Front-end</button>
            <span>➕</span>
            <button onClick={(e) => handleHashMove(e, beRef)} >Back-end</button>
          </div>
          <button onClick={(e) => handleHashMove(e, resumeRef)} >About Nature!</button>
        </div>
        <div className="fe-wrap" ref={feRef}>
          <h2 >Front-end</h2>
          <div>
            <img src={frontEnd} alt='web' />
          </div>
        </div>
        <div className="be-wrap" ref={beRef}>
          <h2 >Back-end</h2>
          <div>
            <img src={backEnd} alt='server' />
          </div>
        </div>
        <div className="resume-wrap" ref={resumeRef}>
          <h2>About Nature</h2>
          <div>
            <Resume />
          </div>
        </div>
      </div>
    </>
  )
}
export default Home

// nature-web-vue/src/components/Home.vue
<template>
  <div class="breadcrumb" ref="brcRef">
    <div class='portfolio-link'>
      <span>포트폴리오 </span>
      <button @click.prevent="handleHashMove($event, feRef)">Front-end</button>
      <span>➕</span>
      <button @click.prevent="handleHashMove($event, beRef)">Back-end</button>
    </div>
    <button @click.prevent="handleHashMove($event, resumeRef)">About Nature!</button>
  </div>
  <div class="fe-wrap" ref="feRef">
    <h2>Front-end</h2>
    <div>
      <img :src="frontEnd" alt='web' />
    </div>
  </div>
  <div class="be-wrap" ref="beRef">
    <h2>Back-end</h2>
    <div>
      <img :src="backEnd" alt='server' />
    </div>
  </div>
  <div class="resume-wrap" ref="resumeRef">
    <h2>About Nature</h2>
    <div>
      <Resume />
    </div>
  </div>
</template>

<script>
import { onMounted, ref } from 'vue'
import * as constants from '@/app/constants'
import Resume from '@/components/Resume.vue'

const frontEndx = constants.GET_FIREBASE_FILE_URL("images", "nature_web.png");
const backEndx = constants.GET_FIREBASE_FILE_URL("images", "nature_server.png");

export default {
  components: {
    Resume,
  },
  emits: ['set-top'],
  setup(props, context) {

    const frontEnd = ref()
    frontEnd.value = frontEndx

    const backEnd = ref()
    backEnd.value = backEndx


    const brcRef = ref(null)
    const feRef = ref(null)
    const beRef = ref(null)
    const resumeRef = ref(null)


    const handleHashMove = (e, targetRef) => {
      let breadcrumbHeight = brcRef.value.clientHeight || 0
      let h = targetRef.offsetTop - (breadcrumbHeight);
      context.emit('set-top', h) // home.vue 함수 호출
    }

    return {
      frontEnd,
      backEnd,
      handleHashMove,
      brcRef,
      feRef,
      beRef,
      resumeRef,
    }
  }
}
</script>
