// nature-web/src/containers/User/User.tsx
import React from "react";
import { Navigate, Route, Routes } from "react-router-dom";
import Login from "../../components/User/Login";
import SignUp from "../../components/User/SignUp";
import './User.css';
import { useSelector } from "react-redux";
import Footer from "../../components/Footer/Footer";
import { RootState } from "../../app/store";

const User: React.FC = () => {
  const user = useSelector((state: RootState) => state.userReducer);

  return (
    <div className="user-container">
      {(user && user.loggedIn) && (
        <Navigate to="/home" replace={true} />
      )}
      <Routes>
        <Route path="/" element={<Login />} />
        <Route path="/signup" element={<SignUp />} />
      </Routes>
      <Footer />
    </div>
  );
}

export default User;

// nature-web-vue/src/pages/user/index.vue
<template>
  <div class="user-container">
    <router-view></router-view>
    <Footer></Footer>
  </div>
</template>

<script>
import Footer from '@/components/footer/Footer.vue'
import { onMounted, computed } from 'vue'
import { useStore } from "vuex";
import { useRouter } from 'vue-router'


export default {
  components: {
    Footer,
  },
  setup() {
    const store = useStore();
    const router = useRouter()
    const user = computed(() => store.getters["User/getUser"]);

    onMounted(() => {
      if (user.value.loggedIn) {
        router.replace({
          name: "Home",
        });
      }
    })
  }
}
</script>
<style>
@import "@/assets/css/pages/user.css";
</style>
